soft/thesis/python/diplomawebsite/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='profile/', permanent=False), name='index'),
	url(r'^signup/$', views.ProfileSignup.as_view(), name='signup'),
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.UserProfileView.as_view(), name='user_profile'),
	url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
	url(r'^messages/$', views.MessageList.as_view(), name='messages'),
	url(r'^messages/(?P<pk>\d+)/$', views.MessageView.as_view(), name='message'),
	url(r'^messages/send/$', views.MessageSendView.as_view(), name='message_send'),
)

soft/thesis/python/diplomawebsite/diploma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', RedirectView.as_view(url='timetable/', permanent=False), name='index'),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^timetable/', include('timetable.urls', namespace='timetable')),
	url(r'^info/', include('info.urls', namespace='info')),
	url(r'^forum/', include('forum.urls', namespace='forum')),
	url(r'^files/', include('files.urls', namespace='files')),
)

soft/thesis/python/diplomawebsite/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns('',
	url(r'^$', views.Information.as_view(), name='index'),
)

soft/thesis/python/diplomawebsite/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<title>Сайт группы ПИ-301</title>
	{% load static %}
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{% get_static_prefix %}css/base.css" media="all" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
	<script type="text/javascript" src="{% get_static_prefix %}scripts/library.js"></script>
</head>
<body>
<header>
	<img src="{% get_static_prefix %}images/header.png" width="400" />
</header>
<nav>
	{% block navigation %}
	<a href="{% url 'timetable:index' %}">Расписание</a>
	<a href="{% url 'forum:index' %}">Форум</a>
	<a href="{% url 'files:index' %}">Файлы</a>
	<a href="{% url 'info:index' %}">Инфо</a>
	{% endblock %}
</nav>
<section>
{% block content %}{% endblock %}
</section>
</body>
</html>

soft/thesis/python/diplomawebsite/templates/pls_auth.html
<p>Пройти <a href="{% url 'accounts:login' %}?next={% url 'accounts:user_profile' %}">авторизацию</a> или <a href="{% url 'accounts:signup' %}">регистрацию</a>.</p>

soft/thesis/python/diplomawebsite/templates/usermenu.html
<p class="usermenu">
	<a href="{% url 'accounts:user_profile' %}">Моя страница</a>
	<a href="{% url 'accounts:messages' %}">Сообщения</a>
	<a href="{% url 'accounts:logout' %}?next=about:blank">Выход</a>
</p>