soft/thesis/python/diplomawebsite/diploma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', RedirectView.as_view(url='timetable/', permanent=False), name='index'),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^timetable/', include('timetable.urls', namespace='timetable')),
	url(r'^info/', include('info.urls', namespace='info')),
	url(r'^forum/', include('forum.urls', namespace='forum')),
	url(r'^files/', include('files.urls', namespace='files')),
)

soft/thesis/python/diplomawebsite/forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
	url(r'^$', views.PostListView.as_view(), name='index'),
	url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
	url(r'^addpost/$', views.PostAddView.as_view(), name='add_post'),
)

soft/thesis/python/diplomawebsite/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns('',
	url(r'^$', views.Information.as_view(), name='index'),
)

soft/thesis/python/diplomawebsite/forum/models.py
#coding: utf-8
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

class Post(models.Model):
	message = models.CharField('Сообщение', max_length=255)
	user_sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='post_sender_set', verbose_name='Автор')
	sended = models.DateTimeField('Отправлено', auto_now_add=True)
	def __unicode__(self):
		return self.message
	def get_absolute_url(self):
		return reverse('forum:post_detail', args=[self.id])

soft/thesis/python/diplomawebsite/forum/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse
from forum.models import Post
from django.contrib.auth.models import User
from django.db.models import Q

class PostListView(ListView):
	model = Post
class PostDetailView(DetailView):
	model = Post
class PostAddView(CreateView):
	model = Post
	fields = ['message']
	def get_form(self, form_class):
		form = super(PostAddView, self).get_form(form_class)
		form.instance.user_sender_id = self.request.user.id
		return form

soft/thesis/python/diplomawebsite/templates/forum/post_detail.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Форум</h3>
{% if object %}
	<p>
		<i>Сообщение</i>
		<br>
		{{ object.message }}
	</p>
	<p>
		<i>Отправитель:</i> <a href="{{ object.user_sender.get_absolute_url }}">{{ object.user_sender }}</a>
	</p>
	<p><i>Отправлено:</i> {{ object.sended|date:"SHORT_DATETIME_FORMAT" }}</p>
{% else %}
    <p>Нет информации.</p>
{% endif %}
<p><a href="{% url 'forum:add_post' %}">Добавить сообщение</a></p>
{% else %}
<p>Форум недоступен анонимным пользователям.</p>
{% include "pls_auth.html" %}
{% endif %}
{% endblock content %}

soft/thesis/python/diplomawebsite/templates/forum/post_form.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Форум</h3>
<form action="{% url 'forum:add_post' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% else %}
<p>Форум недоступен анонимным пользователям.</p>
{% include "pls_auth.html" %}
{% endif %}
{% endblock content %}

soft/thesis/python/diplomawebsite/templates/forum/post_list.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Форум</h3>
{% if post_list %}
    {% for str in post_list %}
	<div class="forum-message"> 
		<p class="forum-message-text">{{ str.message }}</a></p>
		<p class="forum-message-info">
			<a href="{{ str.user_sender.get_absolute_url }}">{{ str.user_sender }}</a>
			отправил <a href="{{ str.get_absolute_url }}">сообщение</a> в {{ str.sended|date:"SHORT_DATETIME_FORMAT" }}
		</p>
	</div>
    {% endfor %}
{% else %}
    <p>Нет информации.</p>
{% endif %}
<p><a href="{% url 'forum:add_post' %}">Добавить сообщение</a></p>
{% else %}
<p>Форум недоступен анонимным пользователям.</p>
{% include "pls_auth.html" %}
{% endif %}
{% endblock content %}