soft/thesis/python/diplomawebsite/diploma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', RedirectView.as_view(url='timetable/', permanent=False), name='index'),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^timetable/', include('timetable.urls', namespace='timetable')),
	url(r'^info/', include('info.urls', namespace='info')),
	url(r'^forum/', include('forum.urls', namespace='forum')),
	url(r'^files/', include('files.urls', namespace='files')),
)

soft/thesis/python/diplomawebsite/files/urls.py
from django.conf.urls import patterns, url
from files import views

urlpatterns = patterns('',
	url(r'^$', views.FileListView.as_view(), name='index'),
	url(r'^detail/(?P<pk>\d+)/$', views.FileDetailView.as_view(), name='detail'),
	url(r'^upload/$', views.FileUploadView.as_view(), name='upload'),
)

soft/thesis/python/diplomawebsite/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns('',
	url(r'^$', views.Information.as_view(), name='index'),
)

soft/thesis/python/diplomawebsite/files/models.py
#coding: utf-8
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.forms.models import modelform_factory

class StoreFile(models.Model):
	name = models.CharField('Имя файла', max_length=20)
	file = models.FileField('Файл', upload_to='.')
	sended = models.DateTimeField('Добавлен', auto_now_add=True)
	user_sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='uploader_set', verbose_name='Отправитель')
	def get_absolute_url(self):
		return reverse('files:detail', args=[str(self.id)])
	def __unicode__(self):
		return self.name

soft/thesis/python/diplomawebsite/files/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from files.models import StoreFile
from django.contrib.auth.models import User

class FileListView(ListView):
	model = StoreFile
class FileDetailView(DetailView):
	model = StoreFile
class FileUploadView(CreateView):
	model = StoreFile
	fields = ['name', 'file']
	def get_form(self, form_class):
		form = super(FileUploadView, self).get_form(form_class)
		form.instance.user_sender_id = self.request.user.id
		return form

soft/thesis/python/diplomawebsite/templates/files/storefile_detail.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Файл</h3>
{% if object %}
	{% load static %}
	<p><i>Имя:</i> {{ object.name }}</p>
	<p><a href="{% get_media_prefix %}{{ object.file }}">Скачать</a></p>
	<p><i>Автор:</i> <a href="{{ object.user_sender.get_absolute_url }}">{{ object.user_sender }}</a></p>
	<p><i>Закачен:</i> {{ object.sended|date:"SHORT_DATETIME_FORMAT" }}</p>
{% else %}
    <p>Нет информации.</p>
{% endif %}
	<p><a href="{% url 'files:upload' %}">Загрузить файл</a></p>
{% else %}
<p>Файлы недоступны анонимным пользователям.</p>
{% include "pls_auth.html" %}
{% endif %}
{% endblock content %}

soft/thesis/python/diplomawebsite/templates/files/storefile_form.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Загрузка файла</h3>
<form enctype="multipart/form-data" action="{% url 'files:upload' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% else %}
{% include "pls_auth.html" %}
{% endif %}
{% endblock %}

soft/thesis/python/diplomawebsite/templates/files/storefile_list.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Файлы</h3>
{% if storefile_list %}
<table>
	<thead>
		<tr>
			<th>Файл</th>
			<th>Автор</th>
			<th>Закачен</th>
		</tr>
	</thead>
	<tbody>
	{% for str in storefile_list %}
		<tr>
			<td><a href="{{ str.get_absolute_url }}">{{ str.name }}</a></td>
			<td><a href="{{ str.user_sender.get_absolute_url }}">{{ str.user_sender }}</a></td>
			<td>{{ str.sended|date:"SHORT_DATETIME_FORMAT"  }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
{% else %}
    <p>Нет информации.</p>
{% endif %}
	<p><a href="{% url 'files:upload' %}">Загрузить файл</a></p>
{% else %}
<p>Файлы недоступны анонимным пользователям.</p>
{% include "pls_auth.html" %}
{% endif %}
{% endblock content %}