soft/thesis/python/diplomawebsite/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(url='profile/', permanent=False), name='index'),
	url(r'^signup/$', views.ProfileSignup.as_view(), name='signup'),
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.UserProfileView.as_view(), name='user_profile'),
	url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
	url(r'^messages/$', views.MessageList.as_view(), name='messages'),
	url(r'^messages/(?P<pk>\d+)/$', views.MessageView.as_view(), name='message'),
	url(r'^messages/send/$', views.MessageSendView.as_view(), name='message_send'),
)

soft/thesis/python/diplomawebsite/diploma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', RedirectView.as_view(url='timetable/', permanent=False), name='index'),
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	url(r'^timetable/', include('timetable.urls', namespace='timetable')),
	url(r'^info/', include('info.urls', namespace='info')),
	url(r'^forum/', include('forum.urls', namespace='forum')),
	url(r'^files/', include('files.urls', namespace='files')),
)

soft/thesis/python/diplomawebsite/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns('',
	url(r'^$', views.Information.as_view(), name='index'),
)

soft/thesis/python/diplomawebsite/accounts/models.py
#coding: utf-8
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

class Message(models.Model):
	message = models.TextField('Сообщение')
	sended = models.DateTimeField('Отправлено', auto_now_add=True)
	user_reciver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='reciver_set', verbose_name='Получатель')
	user_sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sender_set', verbose_name='Отправитель')
	def get_absolute_url(self):
		return reverse('accounts:message', args=[str(self.id)])
	def __unicode__(self):
		return self.message

soft/thesis/python/diplomawebsite/accounts/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView
from accounts.models import Message
from django.contrib.auth.models import User
from django.db.models import Q

class ProfileView(DetailView):
	model = User
class UserProfileView(ListView):
	model = User
	def get_queryset(self):
		return User.objects.filter(id=self.request.user.id)
class MessageList(ListView):
	model = Message
	def get_queryset(self):
		return Message.objects.filter(Q(user_reciver_id=self.request.user.id) | Q(user_sender_id=self.request.user.id)).order_by('-sended')
class MessageView(DetailView):
	model = Message
class MessageSendView(CreateView):
	model = Message
	fields = ['message', 'user_reciver']
	def get_form(self, form_class):
		form = super(MessageSendView, self).get_form(form_class)
		form.instance.user_sender_id = self.request.user.id
		return form
class ProfileSignup(CreateView):
	model = User
	fields = ['username', 'password', 'first_name', 'last_name', 'email']

soft/thesis/python/diplomawebsite/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<h3>Авторизация</h3>
{% if form.errors %}
<p>Ваши логин и пароль не подошли. Попробуйте еще.</p>
{% endif %}
<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<input type="submit" value="Войти" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

soft/thesis/python/diplomawebsite/templates/accounts/logout.html
{% extends "base.html" %}
{% block content %}
<h3>Выход</h3>
<p>Возвращайтесь!<p>
{% endblock %}

soft/thesis/python/diplomawebsite/templates/accounts/message_detail.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Личные сообщения</h3>
{% if object %}
	<p>
		<i>Сообщение</i>
		<br>
		{{ object.message }}
	</p>
	<p>
		<i>Отправитель:</i> <a href="{{ object.user_sender.get_absolute_url }}">{{ object.user_sender }}</a>
		<br>
		<i>Получатель:</i> <a href="{{ object.user_reciver.get_absolute_url }}">{{ object.user_reciver }}</a>
	</p>
	<p><i>Отправлено:</i> {{ object.sended|date:"SHORT_DATETIME_FORMAT" }}</p>
{% else %}
    <p>Нет информации.</p>
{% endif %}
<p><a href="{% url 'accounts:message_send' %}">Отправить сообщение</a></p>
{% else %}
{% include "pls_auth.html" %}
{% endif %}
{% endblock %}

soft/thesis/python/diplomawebsite/templates/accounts/message_form.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Личные сообщения</h3>
<form action="{% url 'accounts:message_send' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% else %}
{% include "pls_auth.html" %}
{% endif %}
{% endblock %}

soft/thesis/python/diplomawebsite/templates/accounts/message_list.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "usermenu.html" %}
<h3>Личные сообщения</h3>
{% if message_list %}
<table>
<thead>
	<tr>
		<th>Сообщение</th>
		<th>Отправитель</th>
		<th>Получатель</th>
		<th>Время отправки</th>
	</tr>
</thead>
<tbody>
	{% for msg in message_list %}
	<tr>
		<td><a href="{{ msg.get_absolute_url }}">{{ msg.message|truncatechars:20 }}</a></td>
		<td><a href="{{ msg.user_sender.get_absolute_url }}">{{ msg.user_sender }}</a></td>
		<td><a href="{{ msg.user_reciver.get_absolute_url }}">{{ msg.user_reciver }}</a></td>		
		<td>{{ msg.sended|date:"SHORT_DATETIME_FORMAT" }}</td>
	</tr>
	{% endfor %}
</tbody>
</table>
{% else %}
    <p>Нет информации.</p>
{% endif %}
<p><a href="{% url 'accounts:message_send' %}">Отправить сообщение</a></p>
{% else %}
{% include "pls_auth.html" %}
{% endif %}
{% endblock %}